settings:
  legacy:
    force: false
    interval: 0s
schema:
- name: mock api
  path: /Users/severiano/go/src/mock-api-twitch
  commands:
    fmt:
      status: true
    install:
      status: true
    run:
      status: true
  watcher:
    extensions:
    - go
    paths:
    - /
    ignored_paths:
    - .git
    - .realize
    - vendor
